- name: Configure web servers
  hosts: web
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: create directory structure for web documents
      ansible.builtin.file:
        path: /web/html
        state: directory
        mode: '0755'
    - name: copy nginx conf file to server
      ansible.builtin.copy:
        src: ./files/nginx.conf
        dest: /etc/nginx/sites-available/default/nginx.conf
        mode: '0644'
        owner: root
        group: root
    - name: ls /default
      command: ls -a /etc/nginx/sites-available/default
      register: dir_contents
    - name: show contents
      debug:
        msg: "{{ dir_contents }}" 
    - name: create link to nginx config file to enable it
      file: 
        src: /etc/nginx/sites-available/default/nginx.conf
        dest: /etc/nginx/sites-enabled/default
        state: link
    - name: Generate index.html file from template. 
      ansible.builtin.template:
        src: ./templates/index.html.j2
        dest: /web/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
    - name: reload nginx service
      service: 
        name: nginx
        state: reloaded
        enabled: yes 
