all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: 34.212.83.224
          ansible_user: ubuntu
        server-two:
          ansible_host: 54.212.33.218
          ansible_user: ubuntu
